//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCursus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus
    {
        public Campus()
        {
            this.Docenten = new HashSet<Docent>();
        }
    
        public int CampusNr { get; set; }
        public string Naam { get; set; }
        public string Straat { get; set; }
        public string HuisNr { get; set; }
        public string PostCode { get; set; }
        public string Gemeente { get; set; }
        public byte[] Aangepast { get; set; }
    
        public virtual ICollection<Docent> Docenten { get; set; }
    }
}
