//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBierenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soort
    {
        public Soort()
        {
            this.Bieren = new HashSet<Bier>();
        }
    
        public int SoortNr { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<Bier> Bieren { get; set; }
    }
}
