//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultuurhuis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Voorstellingen = new HashSet<Voorstelling>();
        }
    
        public int GenreNr { get; set; }
        public string GenreNaam { get; set; }
    
        public virtual ICollection<Voorstelling> Voorstellingen { get; set; }
    }
}
