//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolePlantenClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plant", Namespace="http://schemas.datacontract.org/2004/07/PlantenServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Plant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrijsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nummer {
            get {
                return this.NummerField;
            }
            set {
                if ((this.NummerField.Equals(value) != true)) {
                    this.NummerField = value;
                    this.RaisePropertyChanged("Nummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prijs {
            get {
                return this.PrijsField;
            }
            set {
                if ((this.PrijsField.Equals(value) != true)) {
                    this.PrijsField = value;
                    this.RaisePropertyChanged("Prijs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPlantenService")]
    public interface IPlantenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlantenService/PlantenMinimumprice", ReplyAction="http://tempuri.org/IPlantenService/PlantenMinimumpriceResponse")]
        ConsolePlantenClient.ServiceReference1.Plant[] PlantenMinimumprice(double minPrijsDecimal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlantenService/PlantenMinimumprice", ReplyAction="http://tempuri.org/IPlantenService/PlantenMinimumpriceResponse")]
        System.Threading.Tasks.Task<ConsolePlantenClient.ServiceReference1.Plant[]> PlantenMinimumpriceAsync(double minPrijsDecimal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlantenServiceChannel : ConsolePlantenClient.ServiceReference1.IPlantenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlantenServiceClient : System.ServiceModel.ClientBase<ConsolePlantenClient.ServiceReference1.IPlantenService>, ConsolePlantenClient.ServiceReference1.IPlantenService {
        
        public PlantenServiceClient() {
        }
        
        public PlantenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlantenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsolePlantenClient.ServiceReference1.Plant[] PlantenMinimumprice(double minPrijsDecimal) {
            return base.Channel.PlantenMinimumprice(minPrijsDecimal);
        }
        
        public System.Threading.Tasks.Task<ConsolePlantenClient.ServiceReference1.Plant[]> PlantenMinimumpriceAsync(double minPrijsDecimal) {
            return base.Channel.PlantenMinimumpriceAsync(minPrijsDecimal);
        }
    }
}
