//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandenStedenTalen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landen
    {
        public Landen()
        {
            this.Steden = new HashSet<Steden>();
            this.Talen = new HashSet<Talen>();
        }
    
        public string LandCode { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<Steden> Steden { get; set; }
        public virtual ICollection<Talen> Talen { get; set; }
    }
}
